# Generated by Django 5.1.3 on 2024-11-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_referencia', models.CharField(help_text='Exemplo: 4.5 - 6.0', max_length=255)),
                ('unidade_si', models.CharField(help_text='Exemplo: g/dL, mmol/L', max_length=50)),
                ('prazo_resultado', models.PositiveIntegerField(help_text='Prazo para resultado em dias')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
