# Generated by Django 5.1.3 on 2024-11-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0002_exame'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analise',
            options={'verbose_name_plural': 'Análises'},
        ),
        migrations.AlterModelOptions(
            name='auditoria',
            options={'verbose_name_plural': 'Auditorias'},
        ),
        migrations.AlterModelOptions(
            name='bancodesangue',
            options={'verbose_name_plural': 'Bancos de Sangue'},
        ),
        migrations.AlterModelOptions(
            name='consumivel',
            options={'verbose_name_plural': 'Materiais e Consumíveis'},
        ),
        migrations.AlterModelOptions(
            name='exame',
            options={'verbose_name_plural': 'Exames'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiais e Consumíveis'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterModelOptions(
            name='resultado',
            options={'verbose_name_plural': 'Resultados'},
        ),
    ]
