# Generated by Django 5.1.3 on 2024-11-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0003_alter_analise_options_alter_auditoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposanguineo',
            options={'verbose_name_plural': 'Tipos de Sanguineos'},
        ),
    ]
