# Generated by Django 5.1.3 on 2024-11-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0004_alter_tiposanguineo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposanguineo',
            options={'verbose_name_plural': 'Tipos Sanguineos'},
        ),
    ]
