# Generated by Django 5.1.1 on 2024-11-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0006_remove_analise_data_solicitacao_remove_analise_preco_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_criacao',
            new_name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_identificacao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='residencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
