# Generated by Django 5.1.3 on 2024-11-22 09:33

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0007_rename_data_criacao_paciente_data_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nacionalidade',
            field=django_countries.fields.CountryField(default=True, max_length=2),
        ),
    ]
