# Generated by Django 5.1.3 on 2024-11-22 09:36

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0008_paciente_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=django_countries.fields.CountryField(default='MZ', max_length=2),
        ),
    ]
