# Generated by Django 5.1.3 on 2024-11-22 09:49

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0009_alter_paciente_nacionalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='exames',
            field=models.ManyToManyField(blank=True, to='app_lab.exame'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidade',
            field=django_countries.fields.CountryField(blank=True, default='MZ', max_length=2, null=True),
        ),
    ]
